<?php

declare(strict_types=1);

require __DIR__ . '/config.php';

try {
    $pdo = db();
    $stmt = $pdo->prepare(
    'SELECT items.title, items.link, items.description, items.pub_date, items.guid, sources.name AS source_name
     FROM items
     JOIN sources ON sources.id = items.source_id
     ORDER BY COALESCE(items.pub_date, items.created_at) DESC
     LIMIT :limit'
);
$stmt->bindValue(':limit', FEED_LIMIT, PDO::PARAM_INT);
$stmt->execute();
$items = $stmt->fetchAll();
} catch (Throwable $e) {
    render_fatal($e);
}

header('Content-Type: application/rss+xml; charset=UTF-8');

$siteUrl = (isset($_SERVER['HTTPS']) ? 'https' : 'http') . '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost') . rtrim(dirname($_SERVER['PHP_SELF'] ?? '/'), '/\\');
$feedUrl = $siteUrl . '/feed.php';

echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
?>
<rss version="2.0">
  <channel>
    <title><?= h(APP_NAME) ?> - Aggregated Feed</title>
    <link><?= h($siteUrl . '/index.php') ?></link>
    <description>RSS aggregation generated by RSS Studio</description>
    <language>ar</language>
    <atom:link href="<?= h($feedUrl) ?>" rel="self" type="application/rss+xml" xmlns:atom="http://www.w3.org/2005/Atom" />
    <?php foreach ($items as $item): ?>
      <item>
        <title><?= h($item['title']) ?></title>
        <link><?= h($item['link']) ?></link>
        <guid isPermaLink="false"><?= h($item['guid']) ?></guid>
        <description><?= h((string)$item['description']) ?></description>
        <?php if (!empty($item['pub_date'])): ?>
          <pubDate><?= h((string)$item['pub_date']) ?></pubDate>
        <?php endif; ?>
        <source url=""><?= h($item['source_name']) ?></source>
      </item>
    <?php endforeach; ?>
  </channel>
</rss>
